// Regression: fictional numerals round-trip and idle microscope life in both engines.
const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{for(const [name,type] of [['chromium',chromium],['webkit',webkit]]){const b=await type.launch(name==='chromium'?{channel:'chrome'}:{}),page=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();
await page.route('**/habitat.mjs*',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('return {reset,stage,react,heartBurst,',"if(canvas.id==='habitat')window.__actors=()=>critters;return {reset,stage,react,heartBurst,")})});
for(const id of ['intertidal','groundwater','petri-dish','shallow-marine']){await page.goto((process.env.BASE_URL||'http://127.0.0.1:8892')+'/isopoda/');await page.evaluate(async id=>{const {createRun}=await import('/isopoda/engine.mjs'),{drawCohort}=await import('/isopoda/collection.mjs'),{habitatConfig}=await import('/isopoda/habitats.mjs'),{setLanguage}=await import('/isopoda/i18n.mjs');setLanguage('zh');const s=createRun(habitatConfig(id).species[0],88,id);s.cohort=drawCohort({unlocked:[],draws:0},88,id);s.arrivalPending=false;localStorage.setItem('isopoda-fugue-v4',JSON.stringify(s))},id);await page.reload();await page.locator('#continueBtn').click();await page.clock.runFor(500);
const before=await page.locator('#instruments').innerText();await page.evaluate(async()=>{(await import('/isopoda/i18n.mjs')).setLanguage('isopod')});await page.clock.runFor(100);assert.doesNotMatch(await page.locator('#instruments').innerText(),/\d/);assert.doesNotMatch(await page.locator('#zoomLevel').innerText(),/\d/);await page.screenshot({path:`/tmp/polish-${name}-${id}-bars.png`});await page.evaluate(async()=>{(await import('/isopoda/i18n.mjs')).setLanguage('zh')});await page.clock.runFor(100);assert.equal(await page.locator('#instruments').innerText(),before);if(id!=='petri-dish'&&id!=='groundwater')assert.match(await page.locator('#zoomLevel').innerText(),/\d/);
if(id==='petri-dish'){for(let i=0;i<12;i++){const a=await page.evaluate(()=>window.__actors()[0].phase);await page.clock.runFor(3000);assert.ok(await page.evaluate(()=>window.__actors()[0].phase)>a)}}
await page.screenshot({path:`/tmp/polish-${name}-${id}.png`});console.log(name,id,'PASS');}
assert.deepEqual(errors,[]);await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
