const assert=require('node:assert/strict');
const {chromium,webkit}=require('playwright');
const base=process.env.BASE_URL||'http://127.0.0.1:8773',engine=process.env.BROWSER||'chromium',out=process.env.QA_OUTPUT||'/tmp';
(async()=>{const b=await (engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})});try{
const page=await b.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/rooftop/arrange/');await page.waitForFunction(()=>window.rooftop);await page.locator('#clear').click();await page.locator('[data-asset=mint]').click();assert.match(await page.locator('#noteName').innerText(),/薄荷/);assert.ok(await page.locator('#noteSources a').count()>=2);assert.equal(await page.locator('#notebookBody a:not(#noteSources a)').count(),0);const links=await page.locator('#noteSources a').evaluateAll(es=>es.map(e=>e.href));assert.equal(links.length,new Set(links).size);
await page.locator('#potSelect').selectOption('foam');let o=(await page.evaluate(()=>rooftop.layout.scenes.north))[0];assert.equal(o.pot,'foam');await page.locator('#rotate').click();await page.screenshot({path:out+'/mint-foam-rotated-'+engine+'.png'});await page.locator('#undo').click();assert.equal((await page.evaluate(()=>rooftop.layout.scenes.north))[0].rotation,0);await page.locator('#undo').click();assert.equal((await page.evaluate(()=>rooftop.layout.scenes.north))[0].pot,undefined);await page.locator('#redo').click();assert.equal((await page.evaluate(()=>rooftop.layout.scenes.north))[0].pot,'foam');await page.reload();await page.waitForFunction(()=>window.rooftop);assert.equal((await page.evaluate(()=>rooftop.layout.scenes.north))[0].pot,'foam');
await page.locator('[data-asset=blueberry]').click();assert.deepEqual(await page.locator('#potSelect option').evaluateAll(nodes=>nodes.map(n=>n.value)),['growbag','deep']);await page.locator('#potSelect').selectOption('growbag');await page.screenshot({path:out+'/blueberry-growbag-'+engine+'.png'});
await page.locator('#search').fill('キンシャチ');assert.equal(await page.locator('.asset-card').count(),1);await page.locator('[data-asset=barrel]').click();await page.locator('#potSelect').selectOption('kutani');await page.screenshot({path:out+'/barrel-kutani-'+engine+'.png'});await page.locator('#duplicate').click();assert.equal((await page.evaluate(()=>rooftop.layout.scenes.north)).at(-1).pot,'kutani');await page.locator('#search').fill('');
const saved=await page.evaluate(()=>rooftop.layout);await page.locator('.transfer summary').click();await page.locator('#layoutText').fill(JSON.stringify(saved));await page.locator('#importText').click();assert.deepEqual(await page.evaluate(()=>rooftop.layout),saved);const corrupted=structuredClone(saved);corrupted.scenes.north[0].pot='nonexistent';await page.locator('#layoutText').fill(JSON.stringify(corrupted));await page.locator('#importText').click();assert.match(await page.locator('#message').innerText(),/花盆/);assert.deepEqual(await page.evaluate(()=>rooftop.layout),saved);
const popup=page.waitForEvent('popup');await page.locator('#preview').click();const preview=await popup;await preview.waitForFunction(()=>window.rooftop);assert.deepEqual(await preview.evaluate(()=>rooftop.layout),saved);await preview.screenshot({path:out+'/plants-upstairs-'+engine+'.png'});await preview.locator('#sceneDoor').click();await preview.screenshot({path:out+'/plants-south-'+engine+'.png'});await preview.close();
const stats=await page.evaluate(async()=>{const {PLANTS}=await import('/rooftop/botany.mjs'),{paintObject,ASSETS}=await import('/rooftop/scene.mjs');const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const c=canvas.getContext('2d'),hashes=new Set();let checked=0;for(const a of ASSETS)for(const rotation of [0,90,180,270]){c.clearRect(0,0,128,128);paintObject(c,{type:a.id,x:64,y:64,scale:1,rotation});const data=c.getImageData(0,0,128,128).data;for(const [x,y] of [[2,2],[125,2],[2,125],[125,125]])if(data[(y*128+x)*4+3]!==0)throw Error('Opaque backing '+a.id);const shadow=[];for(let i=0;i<data.length;i+=4)if(data[i+3]>0&&data[i+3]<80)shadow.push({x:(i/4)%128,y:Math.floor(i/4/128)});if(!shadow.length)throw Error('Missing shadow '+a.id);if(shadow.some(p=>p.y<64))throw Error('Rotating shadow '+a.id);checked++;if(rotation===0&&PLANTS.some(p=>p.id===a.id))hashes.add(Array.from(data).join(','));}return {checked,assetCount:ASSETS.length,uniquePlants:hashes.size}});assert.equal(stats.checked,stats.assetCount*4);assert.equal(stats.uniquePlants,58);
await page.setViewportSize({width:390,height:844});await page.locator('[data-asset=strawberry]').click();await page.locator('#potSelect').selectOption('foam');await page.locator('#notebookTitle').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/notebook-mobile-'+engine+'.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('#potSelect').isVisible(),true);assert.deepEqual(errors,[]);console.log(JSON.stringify({engine,passed:true,...stats,checks:'notebook, references, constrained pots, change/undo/redo, persistence, duplication, multilingual search, import rejection, upstairs preview, mobile, all object rotations and transparent corners'}));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
