import {drawTick} from './tick/sprite.mjs';
import {phenotypeFor} from './isopoda/phenotypes.mjs';
import {renderModel,pixelAnatomy} from './isopoda/sprites.mjs';
// A visual average of the original land-isopod render templates, not a taxon.
const IDS=['dairy','cappuccino','diablo','echinatus','pink','coros','bolivari','ducky','daxin','ember','amber','vex','orange'];
function average(values){const first=values[0];if(typeof first==='number'){const numbers=values.filter(Number.isFinite);return numbers.reduce((sum,n)=>sum+n,0)/numbers.length}if(Array.isArray(first))return first.map((v,i)=>average(values.map(a=>a?.[i]??v)));if(first&&typeof first==='object')return Object.fromEntries(Object.entries(first).map(([k,v])=>[k,average(values.map(o=>o?.[k]??v))]));return first}
export function averageIsopodVisual(){const visual=average(IDS.map(phenotypeFor));visual.patterns=[];visual.palette={tergite:'#a8aa8d',cephalon:'#919778',epimera:'#69765a',pleon:'#98a17c',pleotelson:'#828f6c',uropods:'#64765a',antennae:'#485c43',legs:'#465c43',dark:'#3d533c',light:'#bdbea0'};visual.surface={...visual.surface,material:'matte',translucency:0};return visual}
// Center the occupied pixels, including legs and antennae, without resizing the artwork.
function centered(source,dest){const g=source.getContext('2d'),pixels=g.getImageData(0,0,source.width,source.height).data;let l=source.width,t=source.height,r=-1,b=-1;for(let y=0;y<source.height;y++)for(let x=0;x<source.width;x++)if(pixels[(y*source.width+x)*4+3]){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}const c=dest.getContext('2d');c.clearRect(0,0,dest.width,dest.height);c.imageSmoothingEnabled=false;if(r>=l)c.drawImage(source,l,t,r-l+1,b-t+1,Math.round((dest.width-(r-l+1))/2),Math.round((dest.height-(b-t+1))/2),r-l+1,b-t+1)}
export function paintDesktopIcons(){const tick=document.querySelector('#desktopTick'),isopod=document.querySelector('#desktopIsopod');if(tick){const source=document.createElement('canvas');source.width=source.height=28;drawTick(source.getContext('2d'));centered(source,tick)}if(isopod){const source=document.createElement('canvas');source.width=source.height=64;const c=source.getContext('2d');for(const part of pixelAnatomy(renderModel(averageIsopodVisual(),{seed:57}),{posture:'normal'}))for(const [x,y,color] of part.cells){c.fillStyle=color;c.fillRect(y+32,32-x,1,1)}const coarse=document.createElement('canvas');coarse.width=coarse.height=24;const g=coarse.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(source,0,0,24,24);const scaled=document.createElement('canvas');scaled.width=isopod.width;scaled.height=isopod.height;const d=scaled.getContext('2d');d.imageSmoothingEnabled=false;d.drawImage(coarse,0,0,scaled.width,scaled.height);centered(scaled,isopod)}}
