import test from 'node:test';import assert from 'node:assert/strict';
import {createRun,choose,advance,ensureScene,validRun} from '../isopoda/engine.mjs';
import {environmentFor,changeEnvironment,ageEnvironment,environmentTarget} from '../isopoda/environment.mjs';
import {makeIndividuals,stepIndividuals} from '../isopoda/behaviors.mjs';
test('old saves acquire spatial memory without losing records, day or feedback',()=>{const s=createRun('dairy',12);s.day=4;s.stage='feedback';s.feedback='旧记录';s.records=[{text:'旧记录'}];const before=JSON.stringify(s);environmentFor(s);assert.equal(validRun(s),true);const {environment,...old}=s;assert.equal(JSON.stringify(old),before);assert.deepEqual(environmentFor(JSON.parse(JSON.stringify(s))),environment)});
test('leaf choice is atomic and persists in the same location through turns and reload',()=>{let s=createRun('dairy',42);ensureScene(s);assert.ok(choose(s,'leaf'));const leaf={...s.environment.leaves.at(-1)};assert.equal(choose(s,'leaf'),false);for(let n=0;n<6;n++){advance(s);choose(s,s.scene.options.at(-1).id);s=JSON.parse(JSON.stringify(s))}const restored=s.environment.leaves.find(l=>l.id===leaf.id);assert.equal(restored.x,leaf.x);assert.equal(restored.y,leaf.y);assert.ok(restored.age>0)});
test('watering leaves a spatial gradient, ventilation dries it and time does not move leaves',()=>{const s=createRun();const e=environmentFor(s),before=e.wetZones[0].moisture;changeEnvironment(s,'wet-all');assert.equal(e.wetZones.length,2);assert.ok(e.wetZones[0].moisture>before);assert.notEqual(e.wetZones[0].moisture,e.wetZones[1].moisture);const wet=e.wetZones[0].moisture;changeEnvironment(s,'air');ageEnvironment(s);assert.ok(e.wetZones[0].moisture<wet);assert.equal(e.leaves[0].x,275)});
test('food dwindles to crumbs, lifted bark and scuffs survive and disturbance settles',()=>{const s=createRun();const e=environmentFor(s);changeEnvironment(s,'food');assert.equal(e.foodNodes.length,2);changeEnvironment(s,'clean');assert.equal(e.foodNodes.reduce((n,f)=>n+f.amount,0),0);changeEnvironment(s,'lift');assert.notEqual(e.shelter.x,190);for(let i=0;i<4;i++)ageEnvironment(s);assert.equal(e.disturbance,0);assert.equal(e.scuffs.length,2);assert.equal(e.foodNodes.length,2)});
test('persistent food and shelter influence uninvolved individuals after immediate effects end',()=>{const s=createRun('dairy',22);s.humidity=90;environmentFor(s);const c=makeIndividuals(s.seed)[0],target=environmentTarget(s,c);assert.equal(target.kind,'food');c.x=target.x-12;c.y=target.y;c.ambientAction='forage';c.ambientSlot=Math.floor((30+c.offset)/(10-c.traits.restlessness*3.5));stepIndividuals([c],{state:s,encounter:{actors:0,place:[20,20],motion:'rest'},time:30});assert.equal(c.posture,'feeding');changeEnvironment(s,'lift');assert.equal(environmentTarget(s,c).kind,'shelter')});
