import test from 'node:test';
import assert from 'node:assert/strict';
import {WEATHER,TIMES,timeOfDay,weatherProfile,makeWeather,foliageOffset,materialColor} from '../rooftop/weather.mjs';
import {litWindows} from '../rooftop/city.mjs';
test('night stages follow the clock and late lights are a strict subset of evening rooms',()=>{assert.deepEqual([0,5,8,17,19,23].map(timeOfDay),['late','dawn','morning','dusk','evening','evening']);for(const uprightCity of [false,true]){const bounds={x:0,y:0,w:640,h:520},key=w=>w.seed+':'+w.index,early=new Set(litWindows(bounds,.42,{uprightCity}).map(key)),late=litWindows(bounds,.045,{uprightCity});assert.ok(late.length>0&&late.length<early.size/3);assert.ok(late.every(w=>early.has(key(w))));}});
test('all weather and time combinations remain finite, distinguishable and transition smoothly',()=>{const states=WEATHER.flatMap(w=>TIMES.map(p=>weatherProfile(w.id,p.id)));assert.ok(states.every(s=>['wind','rain','cloud','fog','night','lamps','lightAmount'].every(k=>Number.isFinite(s[k])&&s[k]>=0)));const clock=makeWeather({condition:'clear',phase:'day'}),before=clock.state;clock.set('condition','heavy');clock.set('phase','late');clock.update(.05);assert.ok(clock.state.rain>0&&clock.state.rain<1);assert.ok(clock.state.lightAmount>before.lightAmount&&clock.state.lightAmount<.82);for(let i=0;i<200;i++)clock.update(.05);assert.equal(clock.state.lightTint,weatherProfile('heavy','late').lightTint);assert.ok(clock.state.rain>.999)});
test('thin foliage responds to wind while succulent bodies stay rigid',()=>{const offsets=wind=>Array.from({length:80},(_,i)=>foliageOffset(-24,0,i*.1,wind,'fern',2));assert.ok(offsets(.32).some(v=>v!==0),'even a gentle breeze has visible leaf movement');assert.ok(Math.max(...offsets(2.1).map(Math.abs))>Math.max(...offsets(.32).map(Math.abs)));assert.ok(Array.from({length:80},(_,i)=>foliageOffset(-24,0,i*.1,2.1,'barrel',2)).every(v=>Math.abs(v)<=1));});

test('material lighting preserves colour separation and sunset distinguishes light from shade',()=>{const s=weatherProfile('clear','dusk');const lit=materialColor(160,155,135,s,.95),shadow=materialColor(160,155,135,s,.18);assert.ok(lit[0]-shadow[0]>40);assert.ok(lit[0]>lit[2]+40);const leaf=materialColor(85,120,65,s,.18);assert.ok(leaf[1]>leaf[0]&&leaf[1]>leaf[2]);const night=weatherProfile('clear','late');assert.ok(materialColor(165,160,140,night,.5)[1]-materialColor(60,65,45,night,.5)[1]>40)});
test('water accumulates in rain and remains while the roof dries after clearing',()=>{const clock=makeWeather({condition:'clear',phase:'day'});clock.set('condition','heavy');for(let i=0;i<100;i++)clock.update(.05);const water=clock.state.wetness;assert.ok(water>.8);clock.set('condition','clear');for(let i=0;i<100;i++)clock.update(.05);assert.ok(clock.state.rain<.001);assert.ok(clock.state.wetness>water*.7&&clock.state.wetness<water)});

test('daytime stages and map orientations have distinct solar directions',async()=>{const {shadowVector}=await import('../rooftop/weather.mjs');assert.deepEqual([6,9,12,15,18].map(timeOfDay),['dawn','morning','day','afternoon','dusk']);for(const phase of ['dawn','morning','day','afternoon','dusk']){const n=shadowVector(phase),s=shadowVector(phase,'south');assert.equal(s.x,n.y);assert.equal(s.y,-n.x)}assert.ok(shadowVector('dawn').x<0);assert.ok(shadowVector('dusk').x>0);assert.ok(shadowVector('day').y<0);assert.equal(shadowVector('day').x,0)});
