import test from 'node:test';
import assert from 'node:assert/strict';
import {PLANTS,plant,allowedPots} from '../rooftop/botany.mjs';
import {EXPANSION} from '../rooftop/botany-expansion.mjs';
import {ASSETS,asset,fits,supportedLayout,validateLayout,contactPoints,inside} from '../rooftop/scene.mjs';
import {plantContact} from '../rooftop/plant-art.mjs';
import {OBJECTS,lampPower} from '../rooftop/objects.mjs';
import {weatherProfile,plantFlexibility} from '../rooftop/weather.mjs';
const object=(type,x=312,y=240,extra={})=>({id:type,type,x,y,scale:1,rotation:0,...extra});
test('expansion adds twenty cactus, twenty succulent and twelve true moss identities with usable sources',()=>{for(const [category,count] of [['仙人掌',20],['多肉',20],['苔藓',12]])assert.equal(EXPANSION.filter(p=>p.category===category).length,count);assert.equal(new Set(PLANTS.map(p=>p.scientific)).size,PLANTS.length);assert.equal(new Set(ASSETS.map(p=>p.id)).size,ASSETS.length);for(const p of EXPANSION){assert.ok(p.note&&p.care&&p.sources.length);assert.ok(allowedPots(p.id).some(v=>v.id===p.defaultPot));for(const s of p.sources)assert.equal(new URL(s.url).protocol,'https:')}assert.ok(OBJECTS.some(o=>o.category==='器具'));assert.ok(OBJECTS.some(o=>o.category==='小物'));assert.ok(!ASSETS.some(o=>o.category==='苔藓与水'));for(const id of ['wardcase','ceramicseat','tinlantern'])assert.ok(asset(id).sources.length)});
test('foliage can overhang, while unsupported bases and shelves outside the roof are rejected',()=>{const shelf=object('shelf',302,110),p=object('new-cooperi',276.25,101,{scale:.5,support:{id:'shelf',surface:'upper'}});assert.ok(fits('north',shelf));assert.ok(!fits('north',p));assert.ok(fits('north',p,[shelf]));assert.ok(contactPoints(p).some(([x,y])=>!inside('north',x,y)));assert.ok(supportedLayout('north',[p,shelf]));assert.ok(!supportedLayout('north',[p]));assert.ok(!fits('north',p,[{...shelf,x:270}]));const data={version:2,scenes:{north:[p,shelf],south:[]}},saved=validateLayout(data);assert.deepEqual(validateLayout(saved),saved);assert.throws(()=>validateLayout({...data,scenes:{north:[p],south:[]}}),/承重点/);assert.throws(()=>validateLayout({...data,scenes:{north:[p,{...shelf,type:'missing'}],south:[]}}),/数据/)});
test('contact strips and source profiles stay valid at all rotations and scales',()=>{for(const p of EXPANSION)for(const rotation of [0,90,180,270])for(const scale of [.5,1,2]){const o=object(p.id,312,240,{rotation,scale});assert.ok(fits('north',o),p.id);assert.ok(contactPoints(o).every(pt=>pt.every(Number.isFinite)));const l=validateLayout({version:2,scenes:{north:[o],south:[]}});assert.equal(l.scenes.north[0].type,p.id);assert.equal(plant(p.id).scientific,p.scientific)}});
test('all garden fixtures light in both night stages and go out by day, with rigid succulent bodies',()=>{assert.equal(lampPower(weatherProfile('clear','day')),0);assert.equal(lampPower(weatherProfile('clear','morning')),0);for(const phase of ['evening','late'])assert.equal(lampPower(weatherProfile('clear',phase)),1);assert.ok(lampPower(weatherProfile('clear','dusk'))>0);assert.equal(OBJECTS.filter(o=>o.light).length,4);assert.ok(plantFlexibility('exp-fan')<plantFlexibility('exp-threads'))});

test('rectangular foam vessels retain their full flat supporting base',()=>{const p=plantContact({type:'mint',pot:'foam'});assert.equal(p.right-p.left,28);assert.ok(p.bottom>p.top)});
