// Museum-inspired garden adaptations, never claims of reproductions or antique plant pots.
const miho = (id, label) => ({
    label: "MIHO MUSEUM · " + label,
    url: "https://www.miho.jp/booth/html/artcon/" + id + ".htm",
  }),
  met = (id, label) => ({
    label: "Met · " + label,
    url: "https://www.metmuseum.org/art/collection/search/" + id,
  });
const records = [
  [
    "antique-shino",
    "志野芒纹浅钵",
    "shallow",
    "#d9d0bd",
    "#eee1cd",
    "#704b37",
    "grass",
    miho("00000283", "志野芒文鉢"),
    "16世纪桃山时期。按高6.4厘米、径28厘米校准浅阔器形，长石白釉，芒草铁绘位于钵内；游戏中增设排水孔。",
  ],
  [
    "antique-nezumi",
    "鼠志野撇口四方钵",
    "square",
    "#503d30",
    "#654938",
    "#e4d8bd",
    "grass",
    miho("00000293", "鼠志野向付"),
    "16世纪桃山时期。参考高5.8厘米、口径14至14.2厘米的深赤褐釉、白色掻落纹、内卷方口、圆形内底与三足，改作栽培钵。",
  ],
  [
    "antique-shino-square",
    "志野铁绘四方向付",
    "square",
    "#e3d9c9",
    "#ded0b9",
    "#59483b",
    "grass",
    miho("00000294", "志野四方向付"),
    "16世纪桃山时期。参考高9.2厘米、口径8.5厘米的四方向付；四面分别简化蛇笼、珠串、堇草与鸢尾铁绘，游戏中增设排水孔。",
  ],
  [
    "antique-nabeshima",
    "锅岛彩绘八角钵",
    "faceted",
    "#dbe0d5",
    "#b9c7c1",
    "#4d7286",
    "flower",
    met(63040, "八角彩绘钵，约1800年"),
    "约1800年江户时期。按高10.2厘米、径21.3厘米校准八角折面与圈足；参考馆藏黑白照中的萝卜枝叶构图，彩色为游戏转译，并非原釉彩复原。",
  ],
  [
    "antique-nabeshima-dish",
    "锅岛青花几何浅盘",
    "shallow",
    "#dae1da",
    "#a2b8be",
    "#395a79",
    "blue",
    met(50344, "几何纹青花盘，18世纪"),
    "18世纪江户时期。参考高5.1厘米、径20.6厘米的浅盘：内面为青花留白同心几何纹，背面三组花枝，圈足带梳齿纹；游戏中增设排水孔。",
  ],
  [
    "antique-kutani-red",
    "九谷赤绘金彩钵",
    "bowl",
    "#e7d8b8",
    "#c0a271",
    "#994a39",
    "imari",
    {
      label: "Cleveland · Kutani Bowl, 1986.173",
      url: "https://www.clevelandart.org/art/1986.173",
    },
    "19世纪早至中期江户时期，馆藏直径45.7厘米。参考内面唐狮、花草与赤绘金彩同心分区；馆方未列高度，游戏腹深和背面绘画为适配。",
  ],
  [
    "antique-celadon",
    "锅岛青瓷三足钵",
    "scallop",
    "#a5c3b7",
    "#c3d4c5",
    "#71988a",
    "plain",
    {
      label: "LACMA · Nabeshima Celadon Bowl",
      url: "https://collections.lacma.org/object/160060",
    },
    "约1700年江户时期。参考高8.26厘米、径28.89厘米的轮花口浅钵，内底山亭、篱笆、树木划花及三只鬼面足；游戏中增设排水孔。",
  ],
  [
    "antique-oribe-jar",
    "志野织部铁绘花器",
    "jar",
    "#c4bba5",
    "#756655",
    "#51453a",
    "grass",
    miho("00000275", "志野織部徳利"),
    "17世纪江户时期。按高20.8、腹径21.6、口径9.7厘米校准鼓腹和窄颈；白釉铁绘，肩部五道凹线作2–1–2分组。曾作花器，不用于换盆。",
  ],
];
export const ANTIQUE_VESSELS = records.map(
  ([id, name, shape, color, rim, ink, pattern, source, note]) => ({
    id,
    name,
    shape,
    color,
    rim,
    ink,
    pattern,
    kind: id === "antique-oribe-jar" ? "decorative" : "ceramic",
    sources: [source],
    note,
    antique: true,
    shapeLabel: shape === "jar" ? "陈设花器" : "古陶瓷风格栽培钵",
  }),
);
export const ANTIQUE_PLANT_POTS = ANTIQUE_VESSELS.filter(
  (p) => p.kind !== "decorative",
).map((p) => p.id);
