import {gardenCamera} from './camera.mjs';
import {makeResident} from './resident.mjs';
import {SCENES,DOORS,ASSETS,asset,initialLayout,paintBase,paintSurroundings,paintDoor,paintObject,paintPerson,makeWalker,dimensions,inside,fits,validateLayout} from './scene.mjs';
const $=id=>document.getElementById(id),editor=document.body.classList.contains('editor'),KEY='umwelt-rooftop-layout-v1';let scene=new URLSearchParams(location.search).get('scene')==='south'?'south':'north',layout=initialLayout(),selected=null,history=[],future=[],category='全部',drag=null,showPerson=true;
try{if(editor||new URLSearchParams(location.search).get('layout')==='local'){const stored=localStorage.getItem(KEY);if(stored)layout=validateLayout(JSON.parse(stored));}}catch{if(editor)$('message').textContent='本机布局无法读取，已恢复初始陈列。'}
const canvas=$('garden'),ctx=canvas.getContext('2d'),base=document.createElement('canvas');base.width=640;base.height=520;const baseCtx=base.getContext('2d');let walker;const cameras={north:{x:96,y:48,w:416,h:440},south:{x:96,y:176,w:448,h:216}};let camera=cameras[scene];const pans={north:{x:0,y:0},south:{x:0,y:0}};let panDrag=null;const zooms={north:1,south:1},pointers=new Map();let pinch=null;const backdrop=document.createElement('canvas'),resident=editor?null:makeResident();if(resident)showPerson=resident.present;
const objects=()=>layout.scenes[scene],selection=()=>objects().find(o=>o.id===selected);function save(){try{localStorage.setItem(KEY,JSON.stringify(layout))}catch{message('本机存储不可用，请导出 JSON 保存。')}}
function message(text){if(editor)$('message').textContent=text}function checkpoint(){history.push(JSON.stringify(layout));if(history.length>80)history.shift();future=[];buttons()}
function buttons(){if(!editor)return;$('undo').disabled=!history.length;$('redo').disabled=!future.length;$('count').textContent=objects().length+' 件';const o=selection();$('selectedName').textContent=o?asset(o.type).name:'挑一件东西';$('objectControls').hidden=!o;if(o){$('posX').value=o.x;$('posY').value=o.y;$('scale').value=o.scale;}}
function rebuild(){if(!editor){zooms[scene]=scene==='north'?1.7:1;pans[scene]=scene==='north'?{x:56,y:-20}:{x:0,y:0};pointers.clear();panDrag=null;pinch=null;}for(const b of document.querySelectorAll('[data-scene]'))b.setAttribute('aria-pressed',String(b.dataset.scene===scene));camera=cameras[scene];fitView();paintBase(baseCtx,scene,{uprightCity:!editor&&scene==='south'});walker=makeWalker(scene,objects);selected=null;buttons();syncPresence();render()}
function changed(){save();buttons();walker.reset()}
function commitMove(o,patch){const before={...o};Object.assign(o,patch);if(!fits(scene,o)){Object.assign(o,before);message('这里超出了阳台边界。');buttons();return false}checkpointBefore(before,o);changed();return true}
function checkpointBefore(before,o){const after={...o};Object.assign(o,before);checkpoint();Object.assign(o,after)}
function findSpace(type,around){const a=asset(type),origin=around||{x:scene==='north'?310:320,y:scene==='north'?240:286};const candidates=[];for(let y=80;y<470;y+=8)for(let x=136;x<516;x+=8){const o={type,x,y,rotation:0,scale:1};if(fits(scene,o))candidates.push(o)}candidates.sort((a,b)=>Math.hypot(a.x-origin.x,a.y-origin.y)-Math.hypot(b.x-origin.x,b.y-origin.y));return candidates.find(o=>!objects().some(p=>{const d=dimensions(p);return Math.abs(o.x-p.x)<(a.w+d.w)/2+2&&Math.abs(o.y-p.y)<(a.h+d.h)/2+2}))||candidates[0]}
function add(type,source){const pos=findSpace(type,source);if(!pos){message('这个物件放不进当前阳台。');return}const o=source?{...source,x:pos.x,y:pos.y,id:crypto.randomUUID()}:{...pos,id:crypto.randomUUID()};if(!fits(scene,o)){o.rotation=0;o.scale=1;}if(objects().length>=400){message('每个阳台最多 400 件物件。');return}checkpoint();objects().push(o);selected=o.id;changed();message('拿出了 '+asset(type).name+'，拖动即可放到天台上。')}
function remove(){const o=selection();if(!o)return;checkpoint();layout.scenes[scene]=objects().filter(p=>p.id!==o.id);selected=null;changed()}
function rotate(){const o=selection();if(o)commitMove(o,{rotation:(o.rotation+90)%360})}
function catalog(){const q=$('search').value.trim();$('assets').replaceChildren();for(const a of ASSETS.filter(a=>(category==='全部'||a.category===category)&&(!q||a.name.includes(q)))){const button=document.createElement('button');button.className='asset-card';button.dataset.asset=a.id;button.title='添加'+a.name;const preview=document.createElement('canvas');preview.width=64;preview.height=64;paintObject(preview.getContext('2d'),{type:a.id,x:32,y:32,scale:a.w>52?.75:1,rotation:0});const name=document.createElement('span');name.textContent=a.name;button.append(preview,name);button.onclick=()=>add(a.id);$('assets').append(button)}$('assetCount').textContent=ASSETS.length+' 种';}
function coords(e){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*camera.w/r.width+camera.x,y=(e.clientY-r.top)*camera.h/r.height+camera.y;return !editor&&scene==='south'?{x:y,y:-x}:{x,y}}function hit(pos){return [...objects()].sort((a,b)=>b.y-a.y).find(o=>{const d=dimensions(o);return Math.abs(pos.x-o.x)<d.w/2+4&&Math.abs(pos.y-o.y)<d.h/2+4})}
for(const button of document.querySelectorAll('[data-scene]'))button.onclick=()=>{scene=button.dataset.scene;for(const b of document.querySelectorAll('[data-scene]'))b.setAttribute('aria-pressed',String(b===button));rebuild()};
if(editor){
 for(const name of ['全部',...new Set(ASSETS.map(a=>a.category))]){const button=document.createElement('button');button.textContent=name;button.setAttribute('aria-pressed',String(name===category));button.onclick=()=>{category=name;for(const b of $('categories').children)b.setAttribute('aria-pressed',String(b===button));catalog()};$('categories').append(button)}
 $('search').oninput=catalog;catalog();
 canvas.onpointerdown=e=>{if(e.button!==0)return;const pos=coords(e),o=hit(pos);selected=o?.id||null;buttons();canvas.focus({preventScroll:true});if(o){drag={id:o.id,dx:pos.x-o.x,dy:pos.y-o.y,before:JSON.stringify(layout),old:{x:o.x,y:o.y}};canvas.setPointerCapture(e.pointerId)}};
 canvas.onpointermove=e=>{if(!drag)return;const o=selection();if(!o)return;const pos=coords(e),step=$('snap').checked?4:1,patch={x:Math.round((pos.x-drag.dx)/step)*step,y:Math.round((pos.y-drag.dy)/step)*step},test={...o,...patch};if(fits(scene,test)){Object.assign(o,patch);buttons()}};
 const finish=()=>{if(!drag)return;const snapshot=drag.before;drag=null;if(snapshot!==JSON.stringify(layout)){history.push(snapshot);if(history.length>80)history.shift();future=[];changed();message('已经放好。')}};canvas.onpointerup=finish;canvas.onpointercancel=finish;canvas.onlostpointercapture=finish;
 $('rotate').onclick=rotate;$('remove').onclick=remove;$('duplicate').onclick=()=>{const o=selection();if(o)add(o.type,o)};
 for(const id of ['posX','posY','scale'])$(id).onchange=()=>{const o=selection();if(o)commitMove(o,{[id==='posX'?'x':id==='posY'?'y':'scale']:Number($(id).value)})};
 $('undo').onclick=()=>{if(!history.length)return;future.push(JSON.stringify(layout));const previous=selected;layout=JSON.parse(history.pop());rebuild();selected=previous;buttons();save()};$('redo').onclick=()=>{if(!future.length)return;history.push(JSON.stringify(layout));const previous=selected;layout=JSON.parse(future.pop());rebuild();selected=previous;buttons();save()};
 $('clear').onclick=()=>{checkpoint();layout.scenes[scene]=[];selected=null;changed();message('天台腾空了，可以从架上重新挑东西。')};$('restore').onclick=()=>{checkpoint();layout.scenes[scene]=initialLayout().scenes[scene];selected=null;changed();message('已恢复此阳台的初始陈列。')};$('person').onchange=()=>showPerson=$('person').checked;
 $('preview').onclick=()=>{save();window.open('../?layout=local&scene='+scene,'_blank','noopener')};
 const load=text=>{try{const imported=validateLayout(JSON.parse(text));checkpoint();layout=imported;rebuild();save();message('北天台、南阳台的陈列均已导入。')}catch(e){message('导入失败：'+e.message)}};
 $('export').onclick=()=>{const text=JSON.stringify(layout,null,2);$('layoutText').value=text;const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='horticultural-era-rooftop-layout.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('已导出两个阳台的陈列。')};$('importButton').onclick=()=>$('importFile').click();$('importFile').onchange=async()=>{const file=$('importFile').files[0];if(file)load(await file.text());$('importFile').value=''};$('importText').onclick=()=>load($('layoutText').value);
 document.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;const o=selection();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$(e.shiftKey?'redo':'undo').click();return}if(!o)return;const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(delta){e.preventDefault();commitMove(o,{x:o.x+delta[0]*(e.shiftKey?8:1),y:o.y+delta[1]*(e.shiftKey?8:1)})}if(e.key.toLowerCase()==='r')rotate();if(['Delete','Backspace'].includes(e.key)){e.preventDefault();remove()}});
}else{
 $('sceneDoor').onclick=()=>{scene=scene==='south'?'north':'south';const url=new URL(location.href);url.searchParams.set('scene',scene);historyNavigation.pushState(null,'',url);rebuild()};
 window.addEventListener('popstate',()=>{scene=new URLSearchParams(location.search).get('scene')==='south'?'south':'north';rebuild()});
 const clampPan=()=>{pans[scene]=gardenCamera(scene,innerWidth,innerHeight,zooms[scene],pans[scene]).pan};
 const zoomAt=(factor,point,world=coords(point))=>{zooms[scene]=Math.max(1,Math.min(2.5,zooms[scene]*factor));fitView();const after=coords(point);pans[scene].x+=scene==='south'?after.y-world.y:world.x-after.x;pans[scene].y+=scene==='south'?world.x-after.x:world.y-after.y;clampPan();fitView();render()};
 const beginGesture=()=>{const ps=[...pointers.values()];if(ps.length>=2){const a=ps[0],b=ps[1],center={clientX:(a.clientX+b.clientX)/2,clientY:(a.clientY+b.clientY)/2};pinch={distance:Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),world:coords(center)};panDrag=null}else if(ps.length===1){const e=ps[0];pinch=null;panDrag={x:e.clientX,y:e.clientY,origin:{...pans[scene]},camera:{...camera}}}else{panDrag=null;pinch=null}};
 canvas.onpointerdown=e=>{if(e.button!==0)return;pointers.set(e.pointerId,{clientX:e.clientX,clientY:e.clientY});canvas.setPointerCapture(e.pointerId);beginGesture()};
 canvas.onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{clientX:e.clientX,clientY:e.clientY});if(pinch&&pointers.size>=2){const [a,b]=[...pointers.values()],distance=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);if(distance>0&&pinch.distance>0)zoomAt(distance/pinch.distance,{clientX:(a.clientX+b.clientX)/2,clientY:(a.clientY+b.clientY)/2},pinch.world);pinch.distance=distance}else if(panDrag){const rect=canvas.getBoundingClientRect();pans[scene]={x:panDrag.origin.x-(e.clientX-panDrag.x)*panDrag.camera.w/rect.width,y:panDrag.origin.y-(e.clientY-panDrag.y)*panDrag.camera.h/rect.height};clampPan();fitView();render()}};
 const finishPan=e=>{pointers.delete(e.pointerId);beginGesture()};canvas.onpointerup=finishPan;canvas.onpointercancel=finishPan;canvas.onlostpointercapture=finishPan;
 canvas.addEventListener('wheel',e=>{e.preventDefault();zoomAt(Math.exp(-e.deltaY*.0015),e)},{passive:false});
 window.addEventListener('resize',()=>{fitView();render()});
}
const historyNavigation=window.history;
function fitView(){if(editor){canvas.width=camera.w;canvas.height=camera.h;return}const view=gardenCamera(scene,innerWidth,innerHeight,zooms[scene],pans[scene]);camera=view.camera;pans[scene]=view.pan;canvas.width=camera.w;canvas.height=camera.h;backdrop.width=camera.w;backdrop.height=camera.h;const bg=backdrop.getContext('2d');bg.translate(-camera.x,-camera.y);if(scene==='south'){bg.rotate(Math.PI/2);paintSurroundings(bg,{x:camera.y,y:-camera.x-camera.w,w:camera.h,h:camera.w},{uprightCity:true})}else paintSurroundings(bg,camera);const d=DOORS[scene],door=$('sceneDoor'),rect=canvas.getBoundingClientRect(),sx=rect.width/camera.w,sy=rect.height/camera.h,w=Math.max(44,((scene==='south'?d.h:d.w)+16)*sx),h=Math.max(44,((scene==='south'?d.w:d.h)+12)*sy);Object.assign(door.style,{left:(((scene==='south'?-d.y:d.x)-camera.x)*sx-w/2)+'px',top:(((scene==='south'?d.x:d.y)-camera.y)*sy-h/2)+'px',width:w+'px',height:h+'px'});door.setAttribute('aria-label',d.label);door.title=d.label;}
function syncPresence(){if(editor)return;$('returnWorld').hidden=scene!=='north';$('dongdongStatus').textContent=resident.status;$('dongdongStatus').hidden=resident.present;canvas.setAttribute('aria-label',SCENES[scene].name+'，'+(resident.present?'东东正在照料植物':resident.status));}

let last=performance.now(),time=0,drawAt=0;
function render(){ctx.imageSmoothingEnabled=false;if(!editor)ctx.drawImage(backdrop,0,0);ctx.save();ctx.translate(-camera.x,-camera.y);if(!editor&&scene==='south')ctx.rotate(Math.PI/2);ctx.drawImage(base,0,0);if(editor&&$('grid').checked){ctx.fillStyle='#747e6338';for(let y=80;y<470;y+=8)for(let x=136;x<520;x+=8)if(inside(scene,x,y))ctx.fillRect(x,y,1,1)}const sprites=objects().map(o=>({y:o.y-(['shelf','woodshelf','table','bench','sink','basin','terrarium','stool'].includes(o.type)?dimensions(o).h/2:0),object:o}));if(showPerson)sprites.push({y:walker.person.y,person:walker.person});sprites.sort((a,b)=>a.y-b.y);for(const s of sprites)if(s.object)paintObject(ctx,s.object,time);else if(!editor&&scene==='south'){ctx.save();ctx.translate(Math.round(s.person.x),Math.round(s.person.y));ctx.rotate(-Math.PI/2);paintPerson(ctx,{...s.person,x:0,y:0},time);ctx.restore()}else paintPerson(ctx,s.person,time);if(selection())paintObject(ctx,selection(),time,true);if(!editor)paintDoor(ctx,scene);ctx.restore()}
function frame(now){const dt=Math.min((now-last)/1000,.1);last=now;time+=dt;if(resident&&resident.update(dt)){showPerson=resident.present;syncPresence();if(showPerson)walker.reset()}if(showPerson)walker.update(dt);if(now-drawAt>50){drawAt=now;render()}requestAnimationFrame(frame)}
rebuild();requestAnimationFrame(frame);
// Read-only runtime state also makes movement and layout behavior inspectable during QA.
window.rooftop={get scene(){return scene},get layout(){return structuredClone(layout)},get person(){return {...walker.person}},get selected(){return selected},get presence(){return resident?{present:resident.present,status:resident.status,remaining:resident.remaining}:null},get camera(){return {...camera}}};
