// Weather is a local scene clock, not a request to an external forecast service.
export const WEATHER=[{id:'clear',name:'晴朗',wind:.32,rain:0,cloud:.2,fog:0,tint:'#c8ba91',shade:.025},{id:'cloudy',name:'多云',wind:.55,rain:0,cloud:.6,fog:0,tint:'#737c7c',shade:.065},{id:'overcast',name:'阴天',wind:.65,rain:0,cloud:1,fog:.05,tint:'#67777e',shade:.14},{id:'rain',name:'小雨',wind:.8,rain:.45,cloud:1,fog:.08,tint:'#506779',shade:.23},{id:'heavy',name:'大雨',wind:1.45,rain:1,cloud:1,fog:.1,tint:'#374e60',shade:.36},{id:'wind',name:'有风',wind:2.1,rain:0,cloud:.48,fog:0,tint:'#7b8073',shade:.06},{id:'mist',name:'薄雾',wind:.23,rain:0,cloud:.65,fog:.32,tint:'#9da6a0',shade:.1}];
export const TIMES=[{id:'dawn',name:'清晨',sky:'#b7bbc4',night:.16,tint:'#baaa99',lamps:.08},{id:'day',name:'白天',sky:'#bdc2cc',night:0,tint:'#abb8bc',lamps:0},{id:'dusk',name:'黄昏',sky:'#a49fae',night:.25,tint:'#9b7765',lamps:.26},{id:'evening',name:'前半夜',sky:'#687388',night:.68,tint:'#1b2b43',lamps:.42},{id:'late',name:'后半夜',sky:'#515e76',night:.82,tint:'#101b30',lamps:.045}];
export function timeOfDay(hour){return hour<5?'late':hour<8?'dawn':hour<17?'day':hour<19?'dusk':hour<24?'evening':'late'}
export function automaticWeather(milliseconds){const sequence=['clear','cloudy','wind','overcast','rain','cloudy','mist','clear','heavy','overcast'];return sequence[((Math.floor(milliseconds/720000)%sequence.length)+sequence.length)%sequence.length]}
const hex=c=>c.match(/[a-f\d]{2}/gi).map(v=>parseInt(v,16));
export function blendColor(a,b,t){const aa=hex(a),bb=hex(b);return '#'+aa.map((v,i)=>Math.round(v+(bb[i]-v)*t).toString(16).padStart(2,'0')).join('')}
export function weatherProfile(condition,phase){const w=WEATHER.find(w=>w.id===condition)||WEATHER[0],p=TIMES.find(p=>p.id===phase)||TIMES[1];return {...w,condition:w.id,phase:p.id,period:p.name,sky:blendColor(p.sky,w.id==='clear'?p.sky:'#899aa5',p.night>.5?.12:.24),night:p.night,lamps:p.lamps,lightTint:blendColor(w.tint,p.tint,p.night>.5?1:p.night>.01?.72:0),lightAmount:Math.min(.82,p.night+w.shade*(1-p.night)),sun:w.id==='clear'?Math.max(0,1-p.night*1.5):w.id==='cloudy'?.35:0}}
export function makeWeather({condition='auto',phase='auto',now=()=>new Date()}={}){let choices={condition:WEATHER.some(w=>w.id===condition)?condition:'auto',phase:TIMES.some(p=>p.id===phase)?phase:'auto'},current=null,target=null;
 function resolve(){const date=now();return weatherProfile(choices.condition==='auto'?automaticWeather(date.getTime()):choices.condition,choices.phase==='auto'?timeOfDay(date.getHours()+date.getMinutes()/60):choices.phase)}
 target=resolve();current={...target};const colours={sky:hex(current.sky),lightTint:hex(current.lightTint)};return {get choices(){return {...choices}},get state(){return {...current}},set(key,value){if(key==='condition')choices.condition=value==='auto'||WEATHER.some(w=>w.id===value)?value:'auto';if(key==='phase')choices.phase=value==='auto'||TIMES.some(p=>p.id===value)?value:'auto';target=resolve()},update(dt){target=resolve();const t=Math.min(1,dt*2.8);for(const key of ['wind','rain','cloud','fog','night','lamps','lightAmount','sun'])current[key]+=(target[key]-current[key])*t;for(const key of ['sky','lightTint']){const next=hex(target[key]);colours[key]=colours[key].map((v,i)=>v+(next[i]-v)*t);current[key]='#'+colours[key].map(v=>Math.round(v).toString(16).padStart(2,'0')).join('');}for(const key of ['condition','phase','period','name'])current[key]=target[key];return {...current}}}}
export function plantFlexibility(form){return ['barrel','cluster','column','pads','rosette','jade','beads','snake','agave','zebra'].includes(form)?.12:['fern','ivy','tails','spider','herb','tiny','needles','spikes','onion','parsley','cosmos'].includes(form)?1:.65}
export function foliageOffset(y,anchor,time,wind,form,seed){const height=Math.min(1,Math.abs(y-anchor)/24),flex=plantFlexibility(form),gust=Math.sin(time*1.35+seed*.37)*.7+Math.sin(time*2.6+seed*.61)*.3;return Math.round(gust*wind*flex*height*2.15)}
const px=(c,x,y,w,h,col)=>{c.fillStyle=col;c.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))};
const wrap=(v,n)=>((v%n)+n)%n;
export function paintSky(c,bounds,state,time,{reduced=false}={}){const {x,y,w,h}=bounds;px(c,x,y,w,h,state.sky);const night=state.night>.45,cloudColor=blendColor(state.sky,night?'#9ba4b0':'#e2dfd4',night?.12:.6);
 if(night){for(let i=0;i<25;i++){const xx=x+wrap(i*137+53,w),yy=y+wrap(i*79+17,h);if(i/25>state.cloud*.7)px(c,xx,yy,1,1,blendColor(state.sky,'#c5c6bc',.55))}if(state.cloud<.8){px(c,x+w*.73,y+h*.13,5,7,'#b7bdba');px(c,x+w*.73+3,y+h*.13,4,5,state.sky)}}
 const count=reduced?5:9;for(let i=0;i<count;i++){if(i/count>state.cloud)continue;const span=28+(i%3)*15,xx=x+wrap(i*117+time*(.65+state.wind)*(reduced?.65:1),w+span)-span,yy=y+wrap(i*67+13,h);const tone=blendColor(state.sky,cloudColor,.6+(i%3)*.12);px(c,xx,yy+6,span,6,tone);px(c,xx+5,yy+2,span*.48,9,tone);px(c,xx+span*.32,yy,span*.4,10,tone);px(c,xx+8,yy+12,span-10,2,blendColor(state.sky,tone,.5));}
 // Small flocks pass through the open air, hidden naturally behind the city and roof.
 if(!night&&state.rain<.2&&state.fog<.2){for(let i=0;i<3;i++){const xx=x+wrap(time*(5+state.wind)+i*12,w+100)-50,yy=y+h*.18+i*5+Math.sin(time*.65+i)*2,flap=Math.floor(time*3+i)%2,ink=blendColor(state.sky,'#414b49',.8);px(c,xx,yy,2,1,ink);px(c,xx-2,yy-(flap?2:0),2,1,ink);px(c,xx+2,yy-(flap?2:0),2,1,ink)}}
}
export function paintLighting(c,w,h,state,time){c.save();c.fillStyle=state.lightTint;c.globalAlpha=Math.min(.84,state.lightAmount+Math.sin(time*.12)*state.cloud*.012*(1-state.night));c.fillRect(0,0,w,h);if(state.fog>.02){c.fillStyle='#bac3c2';c.globalAlpha=state.fog*.42;c.fillRect(0,0,w,h);for(let i=0;i<3;i++){c.globalAlpha=state.fog*.08;const y=wrap(i*h/3+time*state.wind,h+40)-20;c.fillRect(0,Math.round(y),w,22)}}c.restore()}
export function paintRain(c,w,h,state,time,{reduced=false}={}){if(state.rain<.02)return;c.save();c.globalAlpha=.22+state.rain*.18;const count=Math.round((reduced?48:105)*state.rain),col=state.night>.5?'#b4becb':'#d2d7d4';for(let i=0;i<count;i++){const x=wrap(i*137+time*state.wind*11,w+20)-10,y=wrap(i*73+time*(65+state.rain*55),h+25)-15;px(c,x,y,1,3+state.rain*4,col);if(state.wind>1)px(c,x+1,y+3,1,3,col)}c.restore()}
export function paintWetRoof(c,points,state,time){if(state.rain<.02)return;c.save();c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.clip();c.globalAlpha=state.rain*.15;for(let i=0;i<19;i++){const x=151+wrap(i*61,300),y=91+wrap(i*43,350);px(c,x,y,11+i%9,3,'#546e7a');px(c,x+3,y-1,8+i%5,1,'#b2bdba')}c.globalAlpha=state.rain*.42;for(let i=0;i<14;i++){const age=wrap(time*1.4+i*.37,1);if(age>.65)continue;const x=151+wrap(i*83,290),y=97+wrap(i*67,350),r=1+Math.floor(age*3);px(c,x-r,y,r*2+1,1,'#b6c0bd');px(c,x,y-1,1,1,'#9dabac')}c.restore()}

export function paintCloudShade(c,points,state,time){if(state.cloud<.25||state.night>.45)return;c.save();c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.clip();c.globalAlpha=.025*state.cloud*(1-state.night);const x=wrap(time*(1+state.wind)+11,510)-100;px(c,x,118,92,231,'#35464c');px(c,x+70,173,37,113,'#35464c');c.restore()}
