import {createAudioEngine} from '../assets/audio/audio-engine.mjs';
import {startIsopodMusic} from '../assets/audio/music.mjs';
import {attachAudioControls} from '../assets/audio/controls.mjs';
import {getLanguage} from './i18n.mjs';
export const audioEngine=createAudioEngine({music:startIsopodMusic});
const controls=attachAudioControls(audioEngine,{language:getLanguage});
window.addEventListener('load',controls.refresh);window.addEventListener('isopoda:languagechange',()=>queueMicrotask(controls.refresh));
document.addEventListener('pointerdown',event=>{if(event.isTrusted)void audioEngine.unlock()});
document.addEventListener('keydown',event=>{if(event.isTrusted)void audioEngine.unlock()});
document.addEventListener('click',event=>{const button=event.target.closest('button,a');if(!event.isTrusted||!button||button.disabled||button.getAttribute('aria-disabled')==='true')return;const id=button.id;audioEngine.play(/close|prev|back/i.test(id)?'back':/start|settle|next|continue/i.test(id)?'confirm':'click')},true);
document.addEventListener('visibilitychange',()=>{if(document.hidden){controls.close();void audioEngine.suspend()}else void audioEngine.resume()});
window.addEventListener('pagehide',()=>void audioEngine.suspend());window.addEventListener('pageshow',()=>{if(!document.hidden)void audioEngine.resume()});
