import {isIntertidal,TIDE_LEVELS,TIDE_FLOWS,intertidalIndex} from './data/narrative/intertidal.mjs';
import {applyEstuaryWater} from './data/narrative/estuary.mjs';
import {GROUNDWATER_PHASES,groundwaterProgress} from './data/habitats/groundwater-observation.mjs';
// Stable save IDs. No browser or engine dependency: this is the shared configuration boundary.
const LEGACY_ESTUARY=Object.freeze({...{id:'estuary',days:3,names:['河口汽水带','Brackish estuary','河口汽水域'],scene:'estuary',aquatic:true,species:['hookeri','rugicauda','chelipes','carinata'],defaults:{flow:42,oxygen:74,light:48,cover:66,detritus:52,salinity:18,tide:38,algae:58},palette:['#3d4135','#4e5140','#68644d','#8f8263'],plants:10,rocks:0,wood:false,motion:['cling','crawl','swim','crawl'],metrics:['salinity','tide','detritus'],tides:[38,72,88,46,81,63,31,69,92]},encounterPool:'estuary',endingPool:['estuary-calm','estuary-care','estuary-trace']});
const LEGACY_INTERTIDAL={id:"intertidal",days:3,names:["潮间带岩池","Intertidal rock pool","潮間帯の潮だまり"],scene:"intertidal",aquatic:true,species:["serratum","pelagica","granulosa","ischiosetosa","bidentata"],defaults:{flow:58,oxygen:80,light:62,cover:62,detritus:30,salinity:34,tide:24,algae:35},palette:["#324743","#405552","#69736a","#9b9880"],plants:6,rocks:13,wood:false,motion:["cling","crawl","cling","crawl","cling"],metrics:["tide","salinity","flow"],tides:[24,72,94,41,86,58,18,64,90],encounterPool:"intertidal",endingPool:["intertidal-calm","intertidal-care","intertidal-trace"]};
const configs=[
 {id:'terrestrial',days:7,names:['腐殖层','Forest litter','腐植層'],scene:'forest',aquatic:false,defaults:{},species:null},
 {id:'freshwater',days:1,turns:10,sequence:'freshwater-material',untimed:true,names:['淡水腐殖池','Freshwater pool','淡水の腐葉池'],scene:'freshwater',aquatic:true,species:['aquaticus','meridianus','coxalis','hilgendorfii'],defaults:{flow:30,oxygen:68,light:38,cover:65,detritus:55,salinity:0,tide:100,algae:55},palette:['#273b32','#344439','#4e5140','#68634b'],plants:14,rocks:4,wood:true,motion:['crawl','cling','crawl','crawl'],metrics:['flow','oxygen','detritus'],tides:null},
 {id:'groundwater',days:1,turns:8,cohortSize:14,actorScale:.50,sequence:'groundwater-pulse',untimed:true,names:['地下水·石灰岩洞穴','Limestone groundwater cave','石灰岩洞窟の地下水'],scene:'groundwater',aquatic:true,species:['cavaticus','lusitanicus','virei','valdensis'],defaults:{flow:12,oxygen:72,light:8,cover:82,detritus:16,salinity:0,tide:100,algae:6,connectivity:32,seepage:36,input:8},palette:['#171d1c','#242b28','#59605a','#a7a48f'],plants:0,rocks:0,wood:false,motion:['crawl','crawl','crawl','crawl'],metrics:['connectivity','seepage','input'],tides:null},
 {id:'estuary',days:1,turns:6,sequence:'estuary-observation',untimed:true,names:['河口汽水带','Brackish estuary','河口汽水域'],scene:'estuary',aquatic:true,species:['hookeri','rugicauda','chelipes','carinata'],defaults:{flow:24,oxygen:74,light:48,cover:66,detritus:52,salinity:12,tide:72,algae:58},palette:['#3d4135','#4e5140','#68644d','#8f8263'],plants:10,rocks:0,wood:false,motion:['cling','crawl','swim','crawl'],metrics:['salinity','tide','detritus'],tides:null},
 {id:'intertidal',days:3,turns:9,maxTaxa:2,sequence:'intertidal-tide',untimed:true,names:['潮间带岩池','Intertidal rock pool','潮間帯の潮だまり'],scene:'intertidal',aquatic:true,species:['serratum','pelagica','granulosa','ischiosetosa','bidentata','albifrons','hirsuta'],defaults:{flow:12,oxygen:80,light:62,cover:62,detritus:30,salinity:34,tide:24,algae:35},palette:['#324743','#405552','#69736a','#9b9880'],plants:6,rocks:13,wood:false,motion:['cling','crawl','cling','crawl','cling','crawl','cling'],metrics:['tide','salinity','flow'],tides:TIDE_LEVELS},
 {id:'sandy-surf',days:3,sequence:'sandy-observation',names:['沙滩浪区','Sandy surf zone','砂浜の波打ち際'],scene:'sandy-surf',aquatic:true,species:['pulchra','affinis','spinigera'],defaults:{flow:62,oxygen:84,light:72,cover:18,detritus:12,salinity:35,tide:46,algae:6},palette:['#3b625f','#6f8576','#a99b73','#d0bd8a'],plants:0,rocks:0,wood:false,motion:['swim','swim','drift'],metrics:['tide','flow','salinity'],tides:[46,68,88,38,76,94,52,82,32]},
 {id:'shallow-marine',days:3,names:['近岸浅海·藻场','Nearshore seaweed bed','沿岸浅海の藻場'],scene:'shallow-marine',aquatic:true,species:['balthica','emarginata','neglecta','linearis','maculosa'],defaults:{flow:46,oxygen:76,light:54,cover:72,detritus:42,salinity:35,tide:100,algae:78},palette:['#203e3d','#355452','#6d7660','#969375'],plants:24,rocks:5,wood:false,motion:['cling','swim','drift','swim','cling'],metrics:['flow','algae','detritus'],tides:null},
 {id:'abyssal',days:1,turns:15,names:['深海平原','Abyssal plain','深海底平原'],scene:'abyssal',aquatic:true,dialogue:true,cohortSize:1,actorScale:2.10,motionScale:.055,species:['giganteus'],defaults:{flow:12,oxygen:62,light:4,cover:30,detritus:18,salinity:35,tide:100,algae:0,interpretation:0,restraint:0,attention:0},palette:['#10181b','#172225','#223033','#343d3f'],plants:0,rocks:8,wood:false,motion:['crawl'],metrics:['flow','oxygen','detritus'],tides:null},
 {id:'petri-dish',days:3,names:['阿西莫夫的培养皿',"Asimov's dish",'アシモフの培養皿'],scene:'petri-dish',aquatic:true,cohortSize:1,actorScale:4.2,motionScale:.35,species:['uniramea','ischiosetosa','maculosa'],defaults:{flow:10,oxygen:76,light:78,cover:24,detritus:8,salinity:30,tide:100,algae:4},palette:['#2a3330','#56635d','#aab09d','#d7d9c3'],plants:0,rocks:0,wood:false,motion:['crawl','crawl','crawl'],metrics:['light','oxygen','detritus'],tides:null},
];
export const HABITATS=Object.freeze(configs.map(h=>Object.freeze({...h,encounterPool:h.aquatic?h.id:null,endingPool:h.id==='intertidal'?['intertidal-cycle']:h.id==='estuary'?['estuary-notebook']:h.aquatic?[`${h.id}-calm`,`${h.id}-care`,`${h.id}-trace`]:null})));
export function habitatConfig(value){const id=typeof value==='string'?value:value?.habitatId;return id==='intertidal'&&value?.intertidalLegacy===true?LEGACY_INTERTIDAL:id==='estuary'&&value?.estuaryLegacy===true?LEGACY_ESTUARY:HABITATS.find(h=>h.id===(id||'terrestrial'))||HABITATS[0]}
export function habitatLayoutFilename(value){
 const h=habitatConfig(value==='forest'?'terrestrial':value),fallback=h.scene||h.id;
 const slug=String(h.names?.[1]||fallback).toLowerCase().replace(/['’]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||fallback;
 return `habitat-layout-${slug}.json`;
}
export function eligibleSpecies(p,id='terrestrial'){const h=habitatConfig(id);return h.species?h.species.includes(p.id):p.game?.habitatEligible!==false}
export function cycleHabitat(id,direction){return HABITATS[(HABITATS.findIndex(h=>h.id===id)+direction+HABITATS.length)%HABITATS.length].id}
export function advanceWater(s){const h=habitatConfig(s);if(!h.aquatic)return;const turn=(s.day-1)*3+s.period;
 if(isIntertidal(s)){const i=intertidalIndex(s);s.tide=TIDE_LEVELS[i];s.flow=TIDE_FLOWS[i];s.salinity=34;s.light=62;return}
 if(h.sequence==='estuary-observation'){applyEstuaryWater(s);return}
 if(h.sequence==='freshwater-material'){const completed=(Array.isArray(s.records)?s.records:[]).filter(record=>record.kind==='freshwater-material').length,stage=Math.min(4,Math.floor(completed/2));s.flow=30;s.light=38;s.detritus=[55,62,70,78,64][stage];s.oxygen=Math.max(50,68-stage*2);s.salinity=0;s.tide=100;s.algae=55;return}
 if(h.sequence==='groundwater-pulse'){const index=Math.min(3,Math.floor(groundwaterProgress(s)/2));[s.connectivity,s.seepage,s.input,s.flow,s.detritus]=GROUNDWATER_PHASES[index].metrics;s.light=8;s.oxygen=Math.max(58,72+(s.seepage-50)*.08-(s.input-20)*.04);s.salinity=0;s.tide=100;s.algae=6;return}
 if(h.dialogue){s.light=h.defaults.light;s.oxygen=Math.max(5,Math.min(100,s.oxygen+(s.flow-20)*.018-(s.detritus-25)*.012));s.detritus=Math.max(0,s.detritus-.35);s.salinity=h.defaults.salinity;return}
 if(h.tides)s.tide=h.tides[turn%h.tides.length];
 s.light=[42,70,18][s.period];s.oxygen=Math.max(5,Math.min(100,s.oxygen+(s.flow-35)*.055-(s.detritus-35)*.035));
 s.detritus=Math.max(0,s.detritus-2);s.salinity=Math.max(0,Math.min(42,s.salinity+(h.tides?(s.tide<40?.7:-.4):0)));
}
