// Hobby-line evidence for the Panda King complex. These sources document trade usage,
// captive colour lines and common size/pattern descriptions; they are not taxonomic diagnoses.
export const EXTRA_SOURCES_6=[
 {id:'panda-king-cn-2025',level:'B2',type:'CHINESE HOBBY / TRADE',title:'滿滿的水族館 — 熊貓王鼠婦 Cubaris sp. “Panda King”',url:'https://vocus.cc/article/692dad62fd89780001c87ed1',supports:['pandaKing.chinese-name','pandaKing.trade-name','pandaKing.size','pandaKing.colour','pandaKing.hobby-popularity']},
 {id:'pink-panda-cn-2025',level:'B2',type:'CHINESE HOBBY / TRADE',title:'滿滿的水族館 — 粉紅熊貓王鼠婦 Cubaris sp. “Pink Panda King”',url:'https://vocus.cc/article/692f2843fd89780001460197',supports:['pinkPandaKing.chinese-name','pinkPandaKing.lineage','pinkPandaKing.size','pinkPandaKing.colour']},
 {id:'herpeton-panda-king-2026',level:'B1',type:'HOBBY TAXONOMY NOTE',title:'Herpeton Academy — Panda King Isopod',url:'https://academy.herpeton.net/en/caresheets/invertebrates/cubaris-sp-panda-king/',supports:['pandaKing.unresolved-species','pandaKing.captive-culture-label','redPandaKing.same-culture-line']},
 {id:'xoticbugs-panda-king-2026',level:'B2',type:'TRADE / MORPHOLOGY',title:'Xoticbugs — Cubaris sp. “Panda King” collector guide',url:'https://xoticbugs.com/pages/cubaris-sp-panda-king-isopod',supports:['pandaKing.size','pandaKing.dark-pale-banding','pandaKing.morph-list']},
 {id:'xoticbugs-panda-morphs-2026',level:'B2',type:'SELECTIVE BREEDING / HOBBY',title:'Xoticbugs — Isopod morphs and selective breeding guide',url:'https://xoticbugs.com/pages/selective-breeding-isopods',supports:['pandaKing.lineage','pinkPandaKing.selected-line','redPandaKing.selected-line','blackPandaKing.selected-line','citrusPandaKing.selected-line']},
 {id:'postpods-red-panda-2026',level:'B2',type:'TRADE / CAPTIVE LINE',title:'PostPods — Red Panda King Isopods',url:'https://postpods.co.uk/products/red-panda-king-isopods',supports:['redPandaKing.lineage','redPandaKing.orange-red-colour','redPandaKing.pale-bands','pinkPandaKing.derived-from-red-hobby-report']},
 {id:'tc-red-panda-2026',level:'B2',type:'TRADE / CAPTIVE LINE',title:'TC INSECTS — Cubaris sp. “Red Panda”',url:'https://tcinsects.com/product/cubaris-red-panda-isopods/',supports:['redPandaKing.same-culture-line','redPandaKing.orange-red-colour','redPandaKing.pale-bands']},
 {id:'richards-pink-panda-2026',level:'B2',type:'BREEDER LINEAGE NOTE',title:'Richard’s Inverts — Pink Panda King Isopods',url:'https://richardsinverts-store.com/products/cubaris-sp-pink-panda-king',supports:['pinkPandaKing.selected-line','pinkPandaKing.pink-orange-colour','pinkPandaKing.age-colour-change','pinkPandaKing.red-line-origin-hobby-report']},
 {id:'postpods-pink-panda-2026',level:'B2',type:'TRADE / CAPTIVE LINE',title:'PostPods — Pink Panda King Isopods',url:'https://postpods.co.uk/products/pink-panda-king',supports:['pinkPandaKing.lineage','pinkPandaKing.pink-white-colour','pinkPandaKing.line-maintenance']},
 {id:'pangea-citrus-2026',level:'B2',type:'TRADE / SELECTIVE LINE',title:'Pangea Reptile — Cubaris sp. “Citrus”',url:'https://www.pangeareptile.com/products/cubaris-sp-citris-isopods',supports:['citrusPandaKing.selected-line','citrusPandaKing.orange-red-colour','citrusPandaKing.reduced-banding']},
 {id:'tc-citrus-panda-2026',level:'B2',type:'TRADE / SELECTIVE LINE',title:'TC INSECTS — Cubaris sp. “Citrus”',url:'https://tcinsects.com/product/cubaris-citrus-isopods/',supports:['blackPandaKing.band-suppression-hobby-report','citrusPandaKing.panda-line','citrusPandaKing.orange-colour','citrusPandaKing.band-suppression']}
];
