// Species sources support concrete taxonomy, distribution or morphology claims.
// Directory links below remain discovery aids and are never evidence by themselves.
export const sources = [
 {id:'itis-maculatum',level:'A1',type:'TAXONOMY',title:'ITIS — Armadillidium maculatum (Risso, 1816)',url:'https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=594376',supports:['maculatum.taxonomy','maculatum.type-locality']},
 {id:'cambridge-maculatum-2026',level:'A1',type:'DISTRIBUTION / MORPHOLOGY',title:'Distribution and diversity of terrestrial isopods in Canada — A. maculatum account',url:'https://www.cambridge.org/core/journals/canadian-entomologist/article/distribution-and-diversity-of-terrestrial-isopods-isopoda-oniscidea-in-canada-including-new-records-and-a-species-checklist/C413A7873A1E0F943D684431096688EC',supports:['maculatum.range','maculatum.visible-morphology']},
 {id:'itis-klugii',level:'A1',type:'TAXONOMY',title:'ITIS — Armadillidium klugii Brandt, 1833',url:'https://itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=594364',supports:['klugii.taxonomy','klugii.type-locality']},
 {id:'worms-gestroi',level:'A1',type:'TAXONOMY',title:'WoRMS — Armadillidium gestroi Tua, 1900',url:'https://www.marinespecies.org/aphia.php?id=257699&p=taxdetails',supports:['gestroi.taxonomy','gestroi.synonymy','gestroi.type-locality']},
 {id:'itis-versicolor',level:'A1',type:'TAXONOMY',title:'ITIS — Armadillidium versicolor Stein, 1859',url:'https://itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=594464',supports:['versicolor.taxonomy','versicolor.subspecies','versicolor.type-locality']},
 {id:'jcb-aposematism-2025',level:'A1',type:'MORPHOLOGY / DISTRIBUTION',title:'Ďurajková, Tuf & Vittori 2025 — Repugnatorial glands and aposematism in terrestrial isopods',url:'https://academic.oup.com/jcb/article/45/1/ruaf014/8087963',supports:['klugii.size','klugii.colour','klugii.range','gestroi.size','gestroi.colour','gestroi.range','versicolor.size','versicolor.colour','versicolor.range','officinalis.size','officinalis.colour']},
 {id:'worms-hoffmannseggii',level:'A1',type:'TAXONOMY',title:'WoRMS — Porcellio hoffmannseggii Brandt, 1833',url:'https://www.marinespecies.org/aphia.php?p=taxlist&tName=Porcellio+hoffmannseggi',supports:['hoffmannseggii.accepted-spelling','hoffmannseggii.taxonomy']},
 {id:'schmalfuss-hoffmannseggii-1987',level:'A1',type:'MORPHOLOGY',title:'Schmalfuss 1987 — Revision der Gattung Porcellio: P. hoffmannseggii und P. magnificus',url:'https://www.porcellio.nl/_downloads/d2cdeb36a8bf6ca82ada2945ddb41dee',supports:['hoffmannseggii.body-size','hoffmannseggii.uropods','hoffmannseggii.diagnosis']},
 {id:'taiti-rossano-2015',level:'A1',type:'DISTRIBUTION / TAXONOMY',title:'Taiti & Rossano 2015 — Terrestrial isopods from Morocco',url:'https://zenodo.org/records/3999869',supports:['hoffmannseggii.range','hoffmannseggii.diagnosis']},
 {id:'graellsia-hoffmannseggii-2021',level:'A1',type:'DISTRIBUTION',title:'Graellsia 2021 — Iberian records of Porcellio hoffmannseggii',url:'https://graellsia.revistas.csic.es/index.php/graellsia/article/view/641',supports:['hoffmannseggii.range']},

 {id:'gbif-nasatum',level:'A1',type:'TAXONOMY',title:'GBIF — Armadillidium nasatum Budde-Lund, 1885',url:'https://www.gbif.org/species/2203739',supports:['nasatum.taxonomy','nasatum.synonymy','nasatum.vernacular']},
 {id:'shultz-nasatum-2018',level:'A1',type:'MORPHOLOGY',title:'Shultz 2018 — Armadillidium nasatum identification characters',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC6288251/',supports:['nasatum.cephalon','nasatum.pleotelson','nasatum.uropods','nasatum.conglobation']},
 {id:'gbif-granulatum',level:'A1',type:'TAXONOMY',title:'GBIF — Armadillidium granulatum Brandt, 1833',url:'https://www.gbif.org/species/2203769',supports:['granulatum.taxonomy','granulatum.synonymy']},
 {id:'zecchini-montesanto-2019',level:'A1',type:'MORPHOLOGY / DISTRIBUTION',title:'Zecchini & Montesanto 2019 — Postmarsupial stages of Armadillidium granulatum',url:'https://www.tandfonline.com/doi/full/10.1080/07924259.2018.1514329',supports:['granulatum.dorsal-granulation','granulatum.range','granulatum.microhabitat']},
 {id:'gbif-expansus',level:'A1',type:'TAXONOMY',title:'GBIF — Porcellio expansus Dollfus, 1892',url:'https://www.gbif.org/species/6284469',supports:['expansus.taxonomy']},
 {id:'gbif-haasi',level:'A1',type:'TAXONOMY',title:'GBIF — Porcellio haasi Arcangeli, 1925',url:'https://www.gbif.org/species/155572894',supports:['haasi.taxonomy','haasi.original-description']},
 {id:'garcia-porcellio-2017',level:'A1',type:'MORPHOLOGY',title:'Garcia, Robledo & Villar 2017 — Comparative characters of large eastern-Iberian Porcellio',url:'https://www.porcellio.nl/_downloads/54dab6333467771facbf2e693e71067a',supports:['expansus.colour','expansus.cephalon','expansus.antennae','expansus.uropods','haasi.colour','haasi.cephalon','haasi.antennae','haasi.uropods']},
 {id:'gbif-officinalis',level:'A1',type:'TAXONOMY',title:'GBIF — Armadillo officinalis Duméril, 1816',url:'https://www.gbif.org/species/2202347',supports:['officinalis.taxonomy','officinalis.synonymy']},
 {id:'montesanto-officinalis-2018',level:'A1',type:'MORPHOLOGY / NATURAL HISTORY',title:'Montesanto 2018 — Stridulatory apparatus in Armadillo officinalis',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC6288262/',supports:['officinalis.range','officinalis.xeric-ecology','officinalis.nocturnal','officinalis.stridulation']},

 {id:'bmig-vulgare',level:'A1',type:'MORPHOLOGY / SIZE / ECOLOGY',title:'British Myriapod and Isopod Group — Armadillidium vulgare',url:'https://bmig.org.uk/species/armadillidium-vulgare',supports:['vulgare.size','vulgare.colour','vulgare.conglobation','vulgare.microhabitat']},
 {id:'shultz-vulgare-2018',level:'A1',type:'MORPHOLOGY',title:'Shultz 2018 — Armadillidium vulgare identification characters',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC6288251/',supports:['vulgare.cephalon','vulgare.uropods','vulgare.conglobation']},
 {id:'bmig-oniscus-asellus',level:'A1',type:'TAXONOMY / MORPHOLOGY / SIZE',title:'British Myriapod and Isopod Group — Oniscus asellus',url:'https://bmig.org.uk/species/oniscus-asellus-ssp-asellus',supports:['asellus.taxonomy','asellus.size','asellus.body-shape','asellus.surface','asellus.antennae','asellus.microhabitat']},
 {id:'bmig-philoscia-muscorum',level:'A1',type:'MORPHOLOGY / SIZE',title:'British Myriapod and Isopod Group — Philoscia muscorum',url:'https://bmig.org.uk/species/philoscia-muscorum',supports:['muscorum.size','muscorum.body-shape','muscorum.antennae','muscorum.colour','muscorum.runner']},
 {id:'saska-philoscia-2007',level:'A1',type:'MORPHOLOGY / DISTRIBUTION',title:'Saska 2007 — Philoscia muscorum, new terrestrial-isopod record for the Czech Republic',url:'https://www.researchgate.net/publication/266137835_Philoscia_muscorum_Crustacea_Oniscidea_Philosciidae_new_species_of_terrestrial_isopod_for_the_Czech_Republic',supports:['muscorum.range','muscorum.size','muscorum.stepped-outline','muscorum.long-legs','muscorum.runner']},
 {id:'bmig-trachelipus-rathkii',level:'A1',type:'TAXONOMY / MORPHOLOGY / SIZE',title:'British Myriapod and Isopod Group — Trachelipus rathkii',url:'https://bmig.org.uk/species/trachelipus-rathkii',supports:['rathkii.taxonomy','rathkii.size','rathkii.colour','rathkii.antennae','rathkii.ecology']},
 {id:'belarus-trachelipus-2019',level:'A1',type:'MORPHOLOGY',title:'South-eastern Belarus Oniscidea account — Trachelipus rathkii diagnosis',url:'https://en.ecosysttrans.com/publikatsii/ecosystem-transformation-volume-2-no-2-2019/on-the-fauna-of-woodlice-crustacea-isopoda-oniscidea-of-south-eastern-belarus/',supports:['rathkii.size','rathkii.colour','rathkii.antennae','rathkii.tergal-tubercles','rathkii.cephalon']},
 {id:'itis-hemilepistus-reaumuri',level:'A1',type:'TAXONOMY',title:'ITIS — Hemilepistus reaumuri (Audouin, 1826)',url:'https://itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=595330',supports:['reaumuri.taxonomy','reaumuri.accepted-spelling']},
 {id:'ernst-hemilepistus-2020',level:'A1',type:'MORPHOLOGY / FUNCTION',title:'Ernst et al. 2020 — Tergite edge regions in Hemilepistus reaumuri',url:'https://link.springer.com/article/10.1007/s00339-020-03961-0',supports:['reaumuri.anterior-tubercles','reaumuri.burrow-guarding','reaumuri.non-conglobating','reaumuri.cuticle']},
 {id:'ayari-hemilepistus-2016',level:'A1',type:'BEHAVIOUR / ECOLOGY',title:'Ayari et al. 2016 — Family identity of the sub-social desert isopod Hemilepistus reaumurii',url:'https://www.sciencedirect.com/science/article/pii/S0140196316301136',supports:['reaumuri.desert-ecology','reaumuri.family-units','reaumuri.burrows','reaumuri.homing']},

 {id:'gbif-pictum',level:'A1',type:'TAXONOMY',title:'GBIF — Armadillidium pictum Brandt, 1833',url:'https://www.gbif.org/species/2203750',supports:['pictum.taxonomy','pictum.synonymy']},
 {id:'bmig-pictum',level:'A1',type:'MORPHOLOGY / SIZE / ECOLOGY',title:'British Myriapod and Isopod Group — Armadillidium pictum',url:'https://bmig.org.uk/species/armadillidium-pictum',supports:['pictum.size','pictum.mottling','pictum.conglobation','pictum.microhabitat']},
 {id:'gbif-pulchellum',level:'A1',type:'TAXONOMY',title:'GBIF — Armadillidium pulchellum (Zenker, 1798)',url:'https://www.gbif.org/species/2203670',supports:['pulchellum.taxonomy','pulchellum.synonymy']},
 {id:'bmig-pulchellum',level:'A1',type:'MORPHOLOGY / SIZE',title:'British Myriapod and Isopod Group — Armadillidium pulchellum',url:'https://bmig.org.uk/species/armadillidium-pulchellum',supports:['pulchellum.size','pulchellum.mottling','pulchellum.epimera']},
 {id:'gregory-richards-armadillidium-2008',level:'A1',type:'MORPHOLOGY / COLOUR',title:'Gregory & Richards 2008 — Comparison of A. pulchellum, A. pictum and A. vulgare',url:'https://bmig.org.uk/sites/default/files/bulletin/BullBMIG23%20p9-12%20Gregory%26Richards%20Armadillidium.pdf',supports:['pictum.colour','pictum.telson','pictum.first-pereonite','pulchellum.colour','pulchellum.telson','pulchellum.first-pereonite','pulchellum.conglobation']},
 {id:'schmalfuss-klugii-group-2013',level:'A1',type:'TAXONOMY / MORPHOLOGY / COLOUR',title:'Schmalfuss 2013 — Revision of the Armadillidium klugii-group',url:'https://exuvium.net/wp-content/uploads/2023/04/revision-of-the-armadillidium-klugii-group-stuttgarter-beitraege-naturkunde_ns_6_a_0001-0012.pdf',supports:['werneri.taxonomy','werneri.colour-pattern','werneri.diagnosis','werneri.range']},
 {id:'tuf-durajkova-antipredatory-2022',level:'A1',type:'COLOUR / BEHAVIOUR',title:'Tuf & Ďurajková 2022 — Antipredatory strategies of terrestrial isopods',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC9848959/',supports:['werneri.colour','magnificus.orange-colour','magnificus.threat-display']},
 {id:'gbif-spinicornis',level:'A1',type:'TAXONOMY',title:'GBIF — Porcellio spinicornis Say, 1818',url:'https://www.gbif.org/species/6284504',supports:['spinicornis.taxonomy','spinicornis.synonymy']},
 {id:'bmig-spinicornis',level:'A1',type:'MORPHOLOGY / SIZE / ECOLOGY',title:'British Myriapod and Isopod Group — Porcellio spinicornis',url:'https://bmig.org.uk/species/porcellio-spinicornis',supports:['spinicornis.size','spinicornis.dark-head','spinicornis.median-stripe','spinicornis.yellow-mottling','spinicornis.microhabitat']},
 {id:'shultz-spinicornis-2018',level:'A1',type:'MORPHOLOGY',title:'Shultz 2018 — Porcellio spinicornis identification characters',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC6288251/',supports:['spinicornis.size','spinicornis.cephalon','spinicornis.yellow-pattern','spinicornis.flagellum']},
 {id:'gbif-magnificus',level:'A1',type:'TAXONOMY',title:'GBIF — Porcellio magnificus Dollfus, 1892',url:'https://www.gbif.org/species/6284298',supports:['magnificus.taxonomy','magnificus.synonymy']},
 {id:'schmalfuss-magnificus-1987',level:'A1',type:'MORPHOLOGY / SIZE / DISTRIBUTION',title:'Schmalfuss 1987 — Revision der Gattung Porcellio: P. hoffmannseggii und P. magnificus',url:'https://www.porcellio.nl/_downloads/d2cdeb36a8bf6ca82ada2945ddb41dee',supports:['magnificus.size','magnificus.uropods','magnificus.range','magnificus.diagnosis']}
];
export const evidence = [];
export const sourceDirectory = [
 {title:'World List of Isopod Crustaceans',url:'https://www.marinespecies.org/isopoda/',type:'TAXONOMY'},
 {title:'GBIF',url:'https://www.gbif.org/',type:'TAXONOMY'},
 {title:'Catalogue of Life',url:'https://www.catalogueoflife.org/',type:'TAXONOMY'},
 {title:'Isopod Site',url:'https://isopod.site/',type:'TRADE ID'}
];
// Framework references support renderer anatomy and taxon-level visual templates.
// They do not upgrade unresolved hobby trade names to formally identified species.
export const frameworkSources = [
 {id:'external-anatomy',level:'A1',type:'MORPHOLOGY',title:'陆生等足类外部形态与鉴别框架',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC6288251/',supports:['anatomy.cephalon','anatomy.pereon','anatomy.pleon','anatomy.pleotelson','anatomy.uropods','anatomy.antennae','anatomy.pereopods']},
 {id:'armadillidium-venezillo-head-tail',level:'A1',type:'MORPHOLOGY',title:'Rapa Nui Oniscidea identification characters',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC4525033/',supports:['template.armadillidium.cephalon','template.armadillidium.pleotelson','template.armadillidium.uropods','template.venezillo.cephalon','template.venezillo.pleotelson','template.venezillo.uropods','template.conglobation']},
 {id:'ardentiella-reassessment-2025',level:'A1',type:'MORPHOLOGY',title:'Reassessment of Merulanella and allied Armadillidae',url:'https://zenodo.org/records/15055641',supports:['template.ardentiella.cephalon','template.ardentiella.antennae','template.ardentiella.pereon','template.ardentiella.surface','template.ardentiella.noduli-laterales','template.ardentiella.pleotelson','template.ardentiella.uropods','template.ardentiella.runner','template.ardentiella.conglobation']},
 {id:'porcellio-spatulatus-comparison',level:'A1',type:'MORPHOLOGY',title:'Porcellio selomai and comparison with P. spatulatus',url:'https://www.entomologica.es/publicaciones-boletin/art1818',supports:['template.porcellio-spatulatus.cephalon','template.porcellio-spatulatus.antenna-peduncle']},
 {id:'porcellio-scale-setae-2018',level:'A1',type:'MORPHOLOGY',title:'Porcellio identification and scale-setae characters',url:'https://www.entomologica.es/publicaciones-boletin/en/vol72',supports:['template.porcellio.surface','template.porcellio-echinatus.surface','template.porcellio.cephalon','template.porcellio.antennae']},
 {id:'porcellio-bolivari-characters',level:'A1',type:'MORPHOLOGY',title:'Comparative diagnostic characters of large Iberian Porcellio',url:'https://www.porcellio.nl/_downloads/54dab6333467771facbf2e693e71067a',supports:['template.porcellio-bolivari.cephalon','template.porcellio-bolivari.antenna-peduncle','template.porcellio-bolivari.uropods']},
 {id:'biphasic-molt',level:'A1',type:'MORPHOLOGY',title:'Titanethes albus 双相蜕皮',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3335403/',supports:['condition.molt.boundary.P4-P5']}
];
export const sourcesFor=species=>sources.filter(s=>species.evidenceIds.includes(s.id));
