// Visual references: the author's thirteen stamps. Numeric profiles are game tuning, not care prescriptions.
export const SPECIES = [
  {id:'dairy',name:'奶牛',label:'Dairy Cow',taxon:'Porcellio laevis “Dairy Cow”',status:'常用贸易标注；照片不能独立确定种级身份。',shape:'flat',colors:['#d8cbb0','#403e34','#f0dfbb'],pattern:'spots',speed:1.2,wet:68,cover:45,notes:['奶白色甲片上，黑斑的位置各不相同。你本来准备给它们编号，现在开始依赖斑点。','食物旁出现了新的缺口。搬运并没有发生，食物只是变小了一点。','两块相似的黑斑先后经过同一块石头。今天的个体识别仍有商量余地。']},
  {id:'cappuccino',name:'卡布奇诺',label:'Cappuccino',taxon:'Cubaris sp. “Cappuccino”',status:'贸易名；sp. 表示未确定到种。',shape:'round',colors:['#8f6137','#382f27','#d1ae76'],pattern:'bands',speed:.72,wet:78,cover:70,notes:['浅色边缘从木片下露出来。背部的褐色与腐木几乎连在一起。','一只在落叶边缘停下，另一只贴着它经过。两者都没有改变速度。','你在记录上写了“咖啡色”。盒子里没有咖啡。']},
  {id:'diablo',name:'红魔',label:'Red Diablo',taxon:'“Red Diablo” · Armadillidae',status:'旧贸易名 Merulanella sp.；现也标 Ardentiella sp.，本品系归属未由所查修订直接确认。',shape:'round',colors:['#34382d','#d29c4c','#a45035'],pattern:'diablo',speed:1.05,wet:73,cover:50,notes:['暗色背板之间有暖黄色线条。它在树皮高处停了一阵。','红褐色边缘划过苔藓，随后落到阴影里。颜色在暗处变得不重要。','那条醒目的纹路让你很容易找到它。容易被找到的是你眼里的它。']},
  {id:'echinatus',name:'棘纹鼠妇',label:'Echinatus',taxon:'Porcellio echinatus',status:'正式种名；种加词小写，不加品系引号。',shape:'spiny',colors:['#635c48','#373b31','#a69b7a'],pattern:'ridges',speed:.94,wet:62,cover:45,notes:['背板的颗粒在侧光下显得很深。它把身体压在树皮边上。','它从窄缝退出，换了一个角度，再次进去。入口没有变宽。','棘纹没有让这次穿行更快。你仍然把它画得像一副盔甲。']},
  {id:'pink',name:'粉镭射',label:'Pink Laser',taxon:'Cubaris sp. “Pink Laser”',status:'保留邮票贸易名；流通名称有混用，不能据此确认种或其他品系的同物关系。',shape:'round',colors:['#cd9b8d','#976c65','#e6bdab'],pattern:'stripe',speed:.65,wet:78,cover:78,notes:['淡粉色背部中央有一条较暗的线。它很快被叶片遮住。','湿土让浅色身体更显眼。它停在一粒土旁，触角慢慢扫过。','记录上写着粉色。灯熄后，这一栏暂时失去了用途。']},
  {id:'coros',name:'科罗斯',label:'Coros',taxon:'Porcellio spatulatus “Coros”',status:'spatulatus 为正式种名；Coros 是流通中的产地系标签。',shape:'wide',colors:['#b8aa88','#716852','#d7c9a8'],pattern:'stripe',speed:.78,wet:62,cover:50,notes:['宽阔的浅色侧缘紧贴木片，像一小片有边的影子。','身体很宽，却进入了你原以为太窄的缝。高度比面积更有用。','它贴着表面不动。你在平面图上给它留了一个大位置。']},
  {id:'bolivari',name:'玻利瓦里',label:'Bolivari',taxon:'Porcellio bolivari',status:'正式种名；种加词小写，不加品系引号。',shape:'long',colors:['#bca97d','#d1aa45','#ded0a4'],pattern:'stripe',speed:1.15,wet:60,cover:42,notes:['细长的触角先碰到盒壁，身体随后转向。黄色背线越过一片碎叶。','它抬高身体跨过石粒。平面上的捷径原来有高度。','长触角抵达的地方比身体更远。你画的边界略早结束了。']},
  {id:'ducky',name:'黄头鸭',label:'Rubber Ducky',taxon:'Cubaris sp. “Rubber Ducky”',status:'贸易名；补全 sp.，不当作正式种加词。',shape:'round',colors:['#505048','#48443a','#c4a35a'],pattern:'ducky',speed:.6,wet:80,cover:80,notes:['黄色头部露在木片外，深色背部还在阴影里。过了一会儿，头部也消失了。','它缩成较圆的轮廓。等周围安静下来，触角重新伸出。','“鸭”留在标签上。它沿着湿土继续做鼠妇做的事。']},
  {id:'daxin',name:'大新三色',label:'Daxin Tricolour',taxon:'Cubaris sp. “Daxin Tricolour”',status:'贸易名；补全 sp.，未确认正式种。',shape:'round',colors:['#514236','#332f29','#c58a4f'],pattern:'tricolor',speed:.8,wet:76,cover:65,notes:['暖色头部、暗色中段、浅色尾端依次经过叶缘。','你追着浅色尾端看了一会儿。它钻进木片，三种颜色一起离开。','三种颜色只有一个方向。记录表分了三栏。']},
  {id:'ember',name:'余烬蜂',label:'Ember Bee',taxon:'“Ember Bee” · Armadillidae',status:'旧贸易名 Merulanella sp.；现也标 Ardentiella sp.，本品系种级身份未确定。',shape:'round',colors:['#39372e','#ad563a','#d1934e'],pattern:'ember',speed:1.12,wet:72,cover:50,notes:['暗色背板边缘有细窄的橙红色。它越过树皮上一道凸起。','它在较高的木片上停下，触角伸向下面。这里的地面不只有一层。','边缘像余烬，但没有热量。温度计没有为比喻留位置。']},
  {id:'amber',name:'琥珀',label:'Amber',taxon:'Cubaris sp. “Amber”',status:'贸易名；常见别名 Amber Ducky，未确认正式种。',shape:'round',colors:['#b28346','#493d30','#d5aa62'],pattern:'saddle',speed:.68,wet:78,cover:72,notes:['琥珀色身体中间有一块暗带。它贴着树皮下沿移动。','浅色头部钻进叶片，暗带随后经过。尾端比你预想的晚一点消失。','同样的颜色出现在枯叶上。标签只贴在其中一种东西旁边。']},
  {id:'vex',name:'维克斯',label:'Vex',taxon:'Troglodillo sp. “Vex”',status:'邮票写 Cubaris sp. Vex；现常以 Troglodillo sp. 流通，属级按贸易标注，种未确定。',shape:'wide',colors:['#aa804d','#836440','#cfaa76'],pattern:'ridges',speed:.52,wet:76,cover:82,notes:['宽厚的背板露出一小段浅色边缘。其余部分还在木片下面。','它移动得很少，但两次记录的位置并不相同。','你把这段时间记为“没有变化”。稍后发现它已经换了一面朝向。']},
  {id:'orange',name:'橙色额三角',label:'Orange',taxon:'Armadillidium frontetriangulum “Orange”',status:'frontetriangulum 为正式种名；Orange 为色型标签，保留邮票参考。',shape:'round',colors:['#a8783d','#d7b759','#d7a469'],pattern:'dots',speed:.83,wet:66,cover:55,notes:['橙褐色背板上有几列浅点。它在石头旁收拢，轮廓变短了。','身体展开后，浅点重新排成几行。它并没有回到刚才的位置。','你用点的数量辨认它。它用什么辨认这里，表格没有这一项。']}
];
export const speciesById=id=>SPECIES.find(s=>s.id===id)||SPECIES[0];
