import {paintBase,paintObject,initialLayout,validateLayout,asset,dimensions} from '../scene.mjs';
import {paintDongdong} from '../dongdong.mjs';
import {paintPig,wardrobe,dress,OUTFITS,DECORATIONS,ACTIVITIES} from '../wardrobe.mjs';
const $=id=>document.getElementById(id),canvas=$('room'),c=canvas.getContext('2d');let activity='rest';
$('preview').href='../?scene='+(new URLSearchParams(location.search).get('scene')==='south'?'south':'north');
function choices(id,items,current,select){for(const [key,value] of Object.entries(items)){const b=document.createElement('button');b.type='button';b.textContent=Array.isArray(value)?value[0]:value;b.dataset.value=key;b.setAttribute('aria-pressed',String(key===current()));b.onclick=()=>{select(key);for(const child of $(id).children)child.setAttribute('aria-pressed',String(child===b));$('caption').textContent=id==='activities'?'东东正在'+ACTIVITIES[key]+'。':id==='outfits'?'换好了，穿着'+OUTFITS[key][0]+'上楼。':'小猪的装饰：'+DECORATIONS[key]+'。'};$(id).append(b)}}
choices('outfits',OUTFITS,()=>wardrobe.outfit,key=>dress('outfit',key));choices('decorations',DECORATIONS,()=>wardrobe.pig,key=>dress('pig',key));choices('activities',ACTIVITIES,()=>activity,key=>activity=key);
const px=(x,y,w,h,col)=>{c.fillStyle=col;c.fillRect(x,y,w,h)};
let roomLayout=initialLayout();function loadRoom(){try{const saved=localStorage.getItem('umwelt-rooftop-layout-v1');roomLayout=saved?validateLayout(JSON.parse(saved)):initialLayout()}catch{roomLayout=initialLayout()}}loadRoom();addEventListener('storage',loadRoom);addEventListener('pageshow',loadRoom);addEventListener('focus',loadRoom);
canvas.width=208;canvas.height=384;const floor=document.createElement('canvas');floor.width=640;floor.height=520;paintBase(floor.getContext('2d'),'room');
function frame(ms){const t=ms/1000;c.imageSmoothingEnabled=false;c.clearRect(0,0,208,384);c.save();c.translate(-196,-56);c.drawImage(floor,0,0);const sprites=roomLayout.scenes.room.map(o=>({y:o.y-(asset(o.type).furniture?dimensions(o).h/2:0),o}));sprites.push({y:350,person:{x:300,y:350,state:activity,facing:$('facing').value}},{y:370,pig:{x:260,y:370,state:activity==='walk'?'walk':'rest',facing:'east'}});sprites.sort((a,b)=>a.y-b.y);for(const s of sprites)if(s.o)paintObject(c,s.o,t);else if(s.person)paintDongdong(c,s.person,t);else paintPig(c,s.pig,t);c.restore();requestAnimationFrame(frame)}requestAnimationFrame(frame);
window.room={get outfit(){return wardrobe.outfit},get pig(){return wardrobe.pig},get activity(){return activity},get layout(){return structuredClone(roomLayout.scenes.room)}};
